### ISSUE TITLE
Not showing any comic 

### ISSUE THREAD

**Issue by Codekage224** [maforget/ComicRackKeygen#2]
i just updated my phone to android 14 and installed the cracked version today using the force command and it's not showing any of my downloaded comic even tho it's in the selected folder .I've linked the photos too 
![WhatsApp Image 2024-01-12 at 21 07 50_c83eaa1b](https://github.com/maforget/ComicRackKeygen/assets/115528287/ae110dcf-4d1e-42a0-9d52-ffb7dd4b31b1)
![WhatsApp Image 2024-01-12 at 21 07 46_9316789b](https://github.com/maforget/ComicRackKeygen/assets/115528287/cb0457cd-849b-4d9e-b0d0-40edc159eaa8)
![WhatsApp Image 2024-01-12 at 21 11 19_e7cca592](https://github.com/maforget/ComicRackKeygen/assets/115528287/d8b8eb82-e49e-4481-8015-3732d27158ff)
i've tried to reinstall the app for almost 5 times today and also tried install the untouched version but it said something like "cant verify package" or something like that , looking forward for your reply

**Comment by maforget** [comment]
You can install the application 100x times, it won't change anything. Same as with the untouched one. You get an error installing the untouched one because you need to install it via adb (that message was meant for all install on Android 14+, because it's an old App). But even if you installed it, you would get an error saying that market license failed, even if you did buy it before it being taken down from the store. The untouched is basically dead, that's why you need the cracked version. Which did it's job in you being able to install it and use it. 

This is an OLD program not updated for 10 years so it's gonna break. Android have done a LOT of changes in the last versions on how programs can access files from the storage. Restricting them heavily. I personally have a Pixel phone from Google on Android 14, and beside needed to install it via adb with force, it works flawlessly like it used to do 10+ years ago.

This App is mainly meant to be used with the Desktop Client, which is a manager and the App is used to sync selected files for reading. You can dump comics into it like you do, but that isn't really it main use case. Also with the desktop program you can have all matter of metadata, this is also where this App shines.

So either your phone, is less permissive than Google's own devices or your problem is with your files. Nowhere in your pics, do we see actual comics, just a folder. It also says 1 item under that folder (it should be 34), which may mean you never extracted the zip file in the first place. I did download your file and recreated you folder path and it worked no problem (You won't be able to read the pdf).

So if it's your phone that doesn't like you putting files in folder like that, than you need to use the special folder. When selecting folder, press Home -> Local Storage SDCard 1 (1 for internal, 2 for external). It will have a path like `Android/data/cyo.comicrack.viewer/files`, these folder are used just for this app and have all write privilege. If there is any storage problems this is the first thing to try, because this folder isn't restricted like the others. 

![Screenshot_20240115-141250](https://github.com/maforget/ComicRackKeygen/assets/11904426/68fe78ec-b636-456b-9494-5127339d125c)
